service: s3-csv-parser
frameworkVersion: "3"

custom:
  bucket: csv-file-parser
  stateMachineName: csv-process-state-machine
  roleName: amazon-event-bridge-invoke-step-functions

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
  memorySize: 512
  timeout: 180
  environment:
    CHUNK_SIZE: 100000

functions:
  s3FileParser:
    name: lambda-file-processor
    handler: handler.s3FileParser

stepFunctions:
  stateMachines:
    processfile:
      name: ${self:custom.stateMachineName}
      definition:
        StartAt: ProcessChunk
        States:
          ProcessChunk:
            Type: Task
            Resource:
              Fn::GetAtt: [s3FileParser, Arn]
            Next: ChoiceState
          ChoiceState:
            Type: Choice
            Choices:
              - Variable: "$.s3FileParser.results['finished']"
                BooleanEquals: false
                Next: ProcessChunk
              - Variable: "$.s3FileParser.results['finished']"
                BooleanEquals: true
                Next: Finish
            Default: DefaultState
          DefaultState:
            Type: Fail
            Cause: "No Matches!"
          Finish:
            Type: Succeed

resources:
  Resources:
    S3Bucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${self:custom.bucket}
        NotificationConfiguration:
          EventBridgeConfiguration:
            EventBridgeEnabled: true
    Role:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: ${self:custom.roleName}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - "events.amazonaws.com"
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.roleName}
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: "*"
                  Resource: "*"
    EventRule:
      Type: AWS::Events::Rule
      Properties:
        Name: s3-trigger-event
        State: "ENABLED"
        EventPattern:
          source:
            - aws.s3
          detail-type:
            - "Object Created"
          detail:
            bucket:
              name:
                - ${self:custom.bucket}
        Targets:
          - Arn: arn:aws:states:${aws:region}:${aws:accountId}:stateMachine:${self:custom.stateMachineName}
            Id: "${self:custom.stateMachineName}"
            RoleArn: arn:aws:iam::${aws:accountId}:role/${self:custom.roleName}

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-step-functions
