service: s3-trigger
frameworkVersion: '3'

custom:
  bucket: csv-file-parser

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
  memorySize: 512
  timeout: 180
  environment:
    CHUNK_SIZE: 200

functions:
  s3FileParser:
    name: lambda-file-processor
    handler: handler.s3FileParser
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

stepFunctions:
  stateMachines:
    processfile:
      name: fileProcessStateMachine
      definition:
        Comment: "Orchestrates the processing of files of arbitary size"
        StartAt: ProcessChunk
        States:
          ProcessChunk:
            Type: Task
            Resource: 
              Fn::GetAtt: [s3FileParser, Arn]
            Next: ChoiceState
          ChoiceState:
            Type: Choice
            Choices:
              - Variable: "$.s3FileParser.results['finished']"
                BooleanEquals: false 
                Next: ProcessChunk
              - Variable: "$.s3FileParser.results['finished']"
                BooleanEquals: true
                Next: Finish
            Default: DefaultState
          DefaultState:
            Type: Fail
            Cause: "No Matches!"
          Finish:
            Type: Succeed

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-step-functions